language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get install libgsl0ldbl
  - curl -OL http://ftpmirror.gnu.org/automake/automake-1.14.tar.gz
  - tar -xzf automake-1.14.tar.gz
  - cd automake-1.14
  - ./configure 
  - make 
  - sudo make install
  - cd ..
  - git clone https://github.com/kartikkumar/sgp4deorbit sgp4
  - cd sgp4
  - automake --add-missing
  - ./configure
  - make
  - cd ..
  - git clone https://www.github.com/kartikkumar/sml
  - cd sml 
  - git submodule init
  - git submodule update
  - cmake -HSML -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..
  - git clone https://www.github.com/kartikkumar/sam
  - cd sam
  - git submodule init
  - git submodule update
  - cmake -HSAM -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..  

install:
  - cmake -HAtom -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make
  - cd ..

script:
  - cd build
  - ctest -V