language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get install libgsl0ldbl
  - sudo apt-get install automake
  - git clone https://github.com/kartikkumar/sgp4deorbit sgp4
  - cd sgp4
  - ./configure CC=gcc CXX=g++
  - make
  - cd ..
  - git clone https://www.github.com/kartikkumar/sml
  - cd sml 
  - git submodule init
  - git submodule update
  - cmake -HSML -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..
  - git clone https://www.github.com/kartikkumar/sam
  - cd sam
  - git submodule init
  - git submodule update
  - cmake -HSAM -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..  

install:
  - cmake -HAtom -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make
  - cd ..

script:
  - cd build
  - ctest -V