# Copyright (c) 2016, Abhishek Agrawal (abhishek.agrawal@protonmail.com)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

language: cpp

compiler:
  - gcc
  - clang
